-- MySQL Script generated by MySQL Workbench
-- Thu May 14 15:17:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema homework
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homework` ;

-- -----------------------------------------------------
-- Schema homework
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homework` DEFAULT CHARACTER SET utf8 ;
USE `homework` ;

-- -----------------------------------------------------
-- Table `homework`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework`.`member` ;

CREATE TABLE IF NOT EXISTS `homework`.`member` (
  `member_seq` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '회원번호',
  `email` VARCHAR(100) NOT NULL COMMENT '이메일주소',
  `name` VARCHAR(20) NOT NULL COMMENT '이름',
  `nick` VARCHAR(30) NOT NULL COMMENT '별명',
  `password` CHAR(255) NOT NULL COMMENT '비밀번호',
  `phone` VARCHAR(20) NOT NULL COMMENT '전화번호',
  `gender` CHAR(1) NULL COMMENT '성별(F:여성,M:남성)',
  PRIMARY KEY (`member_seq`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework`.`order` ;

CREATE TABLE IF NOT EXISTS `homework`.`order` (
  `member_seq` INT(10) UNSIGNED NOT NULL COMMENT 'MEMBER.MEMBER_SEQ(회원번호)',
  `order_no` CHAR(12) NOT NULL COMMENT '주문번호',
  `product` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '제품명(emoji포함)',
  `payment_date` DATETIME NOT NULL DEFAULT 1000-01-01 00:00:00 COMMENT '결제일시',
  UNIQUE INDEX `order_no_UNIQUE` (`order_no` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
